server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${DB_CONN_URL:jdbc:mysql://localhost:3306/spring-cloud-2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC}
      username: ${DB_USER:root}
      password: ${DB_PWD:root}
      initial-size: 1
      min-idle: 1
      max-active: 20

eureka:
  client:
    # 表示是否将自己注册进 EurekaServer 默认为 true
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息 默认为 true 。单节点无所谓，集群必须设置成 true 才能配合 ribbon 使用负载均衡
    fetchRegistry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment-8001
    prefer-ip-address: true #访问路径可以显示 IP地址

    # 心跳检测和续约时间
    #开发时设置小些,保证服务关闭后注册中心能及时剔除服务

    # Eureka 客户端向服务端发送心跳的时间间隔,单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 1
    # Eureka 服务端在收到最后一次心跳后等待时间上限,单位为秒(默认是90秒)，超时将剔除服务
    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.yky.spring.cloud.domain # 所有Entity别名类所在包